language: julia
os:
  - linux
julia:
  - 1.0
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: 1.0
    - julia: nightly
notifications:
  email: false
codecov: true
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      script: julia --project=docs/ docs/document.jl
      after_success: skip
