name = "RegularExpressions"
uuid = "27faeba3-bc54-5829-b163-df8cb949fe88"
repo = "https://github.com/bramtayl/RegularExpressions.jl.git"
version = "0.0.2"
author = ["Brandon Taylor <brandon.taylor221@gmail.com>"]

[compat]
julia = "1.0"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Documenter"]
